---
- name: installing lamp server on redhat
  hosts: all
  become: true
  tasks:
    - name: update packages and install httpd
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: enable and start httpd
      ansible.builtin.systemd:
        name: httpd
        enabled: yes
        state: restarted
    - name: install php server
      ansible.builtin.yum:
        name: php
        state: present
    - name: copy info.php page
      ansible.builtin.copy:
        content: '<?php phpinfo(); ?>'
        dest: /var/www/html/info.php
    - name: restart httpd
      ansible.builtin.systemd:
        name: httpd
        state: restarted

