---
apiVersion: v1
kind: Pod
metadata:
  name: mysqlvol
  labels:
    app: mysql
    layer: db
spec:
  containers:
    - name: mysql
      image: mysql:8.0.33
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: hema
          mountPath: var/lib/mysql
  volumes:
    - name: hema
      emptyDir:
        sizeLimit: 100Mi
      