---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-vol
  labels:
    app: mysql
    layer: db
spec:
  containers:
    - name: mysql
      image: mysql:8.0.33
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-vol
          mountPath: var/lib/mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_USER
          value: hema
        - name: MYSQL_PASSWORD
          value: rootroot  
        - name: MYSQL_DATABASE
          value: students
  volumes:
    - name: mysql-vol
      persistentVolumeClaim:
        claimName: mysql-pvc