---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: nginx-deploy
      labels:
        app: nginx
        ver: "1.23"
    spec:
      containers:
        - name: nginx-deploy
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP

    