apiVersion: v1 
kind: Pod
metadata:
  name: hema2
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: alpine
      image: alpine   
      args:
        - sleep
        - 15s

