apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-
  labels:
    app: nginx
    purpose: svcdemo
spec:
  replicas: 3
  minReadySeconds: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        -  name: nginx
           image: nginx:1.25
           ports:
             - containerPort: 80
               protocol: TCP