apiVersion: batch/v1
kind: CronJob
metadata:
  name: karampuri
  labels:
    app: batch
spec:
  schedule: '*/2 * * * *'
  JobTemplate:
    metadata:
      labels:
        app: batch
      name: karampuri
    spec:
      selector:
        matchLabels:
          app: batch
      backoffLimit: 6
      template:
        metadata:
          labels:
            app:batch
          name: karampuri
        spec:
          containers:
            - name: hemacontainer
              image: alpine
              command:
                - sleep
                - 10s