apiVersion: v1
kind: Namespace
metadata:
  name: prod
spec:
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-deploy
  Namespace: prod
spec:
  minReadySeconds: 3
  replicas: 4
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: deploysample
          image: shaikkhajabrahim/deploy-sample:v1.0
          ports:
            - name: webPort
              containerPort: 
              protocol: