apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: heema
  labels:
    app: jenkins
    environment: dev
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: jenkins
      version: v1.1
  template:
    metadata:
      name: heema
      labels:
        app: jenkins
        version: v1.1
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
