apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    purpose: Demo
spec:
  type: ExternalName
  externalName: hema-svc-lb
  selector:
     app: nginx
  ports:
      port: 80
      targetPort: 80