apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
    type: Service
spec:
  type: ExternalName
  ports:
    - name: jenkins/jenkins
      port: 8080
      protocol: TCP
      nodePort: 30001