apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
    - name: jenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          protocol: TCP












